### ISSUE TITLE
Getting the dataset

### ISSUE THREAD

**Issue by pommedeterresautee** [kirasystems/science#1]
Hi, 

I am part of an association called OpenLaw promoting open data in legal matters.
Last year we run a project of tagging legal cases for zoning, etc. with the French supreme court and some French  administration (https://openlaw.fr/travaux/communs-numeriques/ia-droit-datasets-dapprentissage).

I think your project (listed in SIGIR) is quite interesting for us and I am wondering to who I may write to get the dataset and replay your script.

Kind regards,
Michaël

**Comment by aroegies** [comment]
Hi,

Thanks for you're interest in the collection. We're currently just finalizing various details wrt to usage agreements and the like. In all likelihood, everything should be live within the next week or two.

I'll post again on this issue when it's live. 

Best,
Adam

**Comment by pommedeterresautee** [comment]
Thanks a lot!

**Comment by aroegies** [comment]
Sorry for such a long gap in response, we had several delays with getting the agreement wording correct as well as ensuring we could make the data readily available. 

In essence, you will submit an executed version of this [agreement](https://kirasystems.com/files/Kira-Systems-Information-Release-Application.pdf) to `science at kirasystems dot com`. Once we've processed it on our end, we'll respond with instructions on how to actually download the data (i.e., you'll be given access to a repository housing the data). 

Best,
Adam
